global using static Application.Heplers.CommonFunctions;
global using Microsoft.Extensions.DependencyInjection;
global using Domain.ViewModels.Authentication;
global using Microsoft.AspNetCore.Identity.Data;
global using Microsoft.Extensions.Configuration;
global using Microsoft.EntityFrameworkCore;
global using Domain.ViewModels.Response;
global using Application.Services.IServices;
global using Microsoft.AspNetCore.Identity;
global using static Application.Heplers.SD;
global using Domain.ViewModels.User;
global using Domain.EntityModels;
global using Application.Services;
global using Application.Heplers;
global using Infrastructure;
global using AutoMapper;
